spring.application.name=TODO-App-Terraform

# MySQL DB
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${MYSQL_ADMIN_LOGIN:}
spring.datasource.password=${MYSQL_ADMIN_PASSWORD:}

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql = TRUE


# JPA Hibernate
spring.jpa.hibernate.ddl-auto=update

###Logging Levels
#Disable the default loggers
logging.level.org = WARN
logging.level.blog = WARN

#Show SQL executed
logging.level.org.hibernate.SQL = DEBUG
logging.level.org.hibernate.type.descriptor = TRACE


spring.mvc.hiddenmethod.filter.enabled=true
